/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CarsDao;
import DAO.UsersDao;
import helpers.Helpers;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Users;

/**
 *
 * @author busyDev
 */
public class ModernAdminView extends javax.swing.JFrame {

    /**
     * Creates new form ModernDashboardLook
     */
    private String username;

    public ModernAdminView() {
        initComponents();
        view_data();
    }

    public ModernAdminView(String username) {
        this.username = username;
        initComponents();
        view_data();
        usernameLabel.setText(username);
    }

    Helpers helperMethods = new Helpers();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        homeLabel = new javax.swing.JLabel();
        addUserLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        homeVeiw = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        carsLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userCountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        UserManagementVeiw = new javax.swing.JPanel();
        roleComboBox = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resetFields = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("e-GARAGE");

        homeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home-light.png"))); // NOI18N
        homeLabel.setText("  Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        addUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        addUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/add-user-light.png"))); // NOI18N
        addUserLabel.setText(" Add Users");
        addUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserLabelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(addUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 670));

        jPanel4.setLayout(new java.awt.CardLayout());

        homeVeiw.setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/users.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/car-mechanic.png"))); // NOI18N

        carsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carsLabel.setText("10 Cars Worked on");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("100+ Hours");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/web-usage.png"))); // NOI18N

        userCountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCountLabel.setText("10 Users");

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Email", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usersTable);

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/refresh.png"))); // NOI18N
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeVeiwLayout = new javax.swing.GroupLayout(homeVeiw);
        homeVeiw.setLayout(homeVeiwLayout);
        homeVeiwLayout.setHorizontalGroup(
            homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeVeiwLayout.createSequentialGroup()
                .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel10))
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel11))
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(carsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(77, 77, 77))
            .addGroup(homeVeiwLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        homeVeiwLayout.setVerticalGroup(
            homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeVeiwLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(homeVeiwLayout.createSequentialGroup()
                        .addGroup(homeVeiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(homeVeiwLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(carsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homeVeiwLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(userCountLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel4.add(homeVeiw, "card3");

        UserManagementVeiw.setBackground(new java.awt.Color(245, 245, 245));
        UserManagementVeiw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roleComboBox.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mechanic", "Cashier" }));
        roleComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 245, 245)));
        UserManagementVeiw.add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 386, 218, 37));

        deleteBtn.setBackground(new java.awt.Color(252, 252, 252));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        UserManagementVeiw.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 458, 74, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Email");
        UserManagementVeiw.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 339, -1, -1));

        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        passwordTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        UserManagementVeiw.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 304, 215, 29));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Role");
        UserManagementVeiw.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 386, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Password");
        UserManagementVeiw.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 303, -1, -1));

        resetFields.setBackground(new java.awt.Color(252, 252, 252));
        resetFields.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetFields.setText("Reset Fields");
        resetFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFieldsActionPerformed(evt);
            }
        });
        UserManagementVeiw.add(resetFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name");
        UserManagementVeiw.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 166, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Last Name");
        UserManagementVeiw.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 214, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Username");
        UserManagementVeiw.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 262, -1, -1));

        fnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fnameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        UserManagementVeiw.add(fnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 167, 215, 29));

        lnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lnameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        UserManagementVeiw.add(lnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 215, 215, 29));

        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        usernameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        UserManagementVeiw.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 263, 215, 29));

        createBtn.setBackground(new java.awt.Color(252, 252, 252));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createBtn.setText("Add User");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        UserManagementVeiw.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 458, 80, 40));

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        UserManagementVeiw.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 339, 215, 29));

        updateBtn.setBackground(new java.awt.Color(252, 252, 252));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        UserManagementVeiw.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 458, 135, 40));

        searchBtn.setBackground(new java.awt.Color(252, 252, 252));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/search_icon.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        UserManagementVeiw.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 36, 49, 38));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        searchTextField.setToolTipText("Search By username");
        searchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 1, true));
        searchTextField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        UserManagementVeiw.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 36, 217, 38));

        jPanel4.add(UserManagementVeiw, "card2");

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 670, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Cool Admin");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 120, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetFields() {
        fnameTextField.setText(" ");
        lnameTextField.setText(" ");
        usernameTextField.setText(" ");
        usernameTextField.setEnabled(true);
        emailTextField.setText(" ");
        passwordTextField.setText(" ");
        this.roleComboBox.setSelectedIndex(1);
        this.roleComboBox.setEnabled(true);
    }

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        helperMethods.logout();
        dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        homeVeiw.setVisible(true);
        UserManagementVeiw.setVisible(false);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void addUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserLabelMouseClicked
        homeVeiw.setVisible(false);
        UserManagementVeiw.setVisible(true);
    }//GEN-LAST:event_addUserLabelMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        view_data();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String fname = fnameTextField.getText().trim();
        String lname = lnameTextField.getText().trim();
        String username = usernameTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String password = passwordTextField.getText().trim();
        String role = this.roleComboBox.getSelectedItem().toString().toLowerCase();
        if (fname.isEmpty() || lname.isEmpty() || username.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "All Inputs are required",
                    "warning",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            if (helperMethods.validateEmail(email)) {
                Users newUser = new Users(fname, lname, username, email, role, password);
                UsersDao dao = new UsersDao();
                String daoResult = dao.createUserPrepared(newUser);
                JOptionPane.showMessageDialog(this, daoResult);
                view_data();
                resetFields();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Invalid email address provided",
                        "warning",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String fname = fnameTextField.getText().trim();
        String lname = lnameTextField.getText().trim();
        String username = usernameTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String password = passwordTextField.getText().trim();
        String role = this.roleComboBox.getSelectedItem().toString().toLowerCase();
        if (fname.isEmpty() || lname.isEmpty() || username.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "All Inputs are required",
                    "warning",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            if (helperMethods.validateEmail(email)) {
                Users userObj = new Users(fname, lname, username, email, role, password);
                UsersDao dao = new UsersDao();
                String daoResult = dao.updateUserPrepared(userObj);
                JOptionPane.showMessageDialog(this, daoResult);
                view_data();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "First Name must be 5 length ",
                        "warning",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String fname = fnameTextField.getText().trim();
        String lname = lnameTextField.getText().trim();
        String username = usernameTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String password = passwordTextField.getText().trim();
        String role = this.roleComboBox.getSelectedItem().toString().toLowerCase();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Username is required",
                    "warning",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            Users userObj = new Users(fname, lname, username, email, role, password);
            UsersDao dao = new UsersDao();
            String daoResult = dao.deleteUserPrepared(userObj);
            JOptionPane.showMessageDialog(this, daoResult);
            resetFields();
            view_data();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchText = searchTextField.getText().trim();

        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username to search is required", "Required Field", JOptionPane.WARNING_MESSAGE);
        } else {
            UsersDao dao = new UsersDao();
            Users user = dao.findUserRecord(searchText);
            if (user != null) {
                fnameTextField.setText(user.getFirstName());
                lnameTextField.setText(user.getLastName());
                usernameTextField.setText(user.getUsername());
                usernameTextField.setEnabled(false);
                emailTextField.setText(user.getEmail());
                passwordTextField.setText(user.getPassword());
                if (user.getRole().equals("cashier")) {
                    this.roleComboBox.setSelectedIndex(1);

                } else if (user.getRole().equals("mechanic")) {
                    this.roleComboBox.setSelectedIndex(0);
                } else {
                    this.roleComboBox.setSelectedItem(null);
                }
                this.roleComboBox.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "User Doesn't exist");
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void resetFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFieldsActionPerformed
        resetFields();
    }//GEN-LAST:event_resetFieldsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModernAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModernAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModernAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModernAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModernAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserManagementVeiw;
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JLabel carsLabel;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homeVeiw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton resetFields;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel userCountLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    private void view_data() {
        /* This methods syncs the display table's data with the database data */
        UsersDao dao = new UsersDao();
        CarsDao cardao = new CarsDao();
        List<Users> users = dao.allUserRecords();
        Iterator iterator = users.iterator();
        DefaultTableModel tblModel = (DefaultTableModel) usersTable.getModel();
        tblModel.setRowCount(0);
        Integer carsCount = cardao.getCarsCount();
        int usersCount = 0;
        
        if (users != null) {
            for (Users tempUser : users) {
                String userId = String.valueOf(tempUser.getId());
                String name = tempUser.getFirstName() + " " + tempUser.getLastName();
                String username = tempUser.getUsername();
                String email = tempUser.getEmail();
                String role = tempUser.getRole();

                String tbData[] = {userId, name, username, email, role};
                tblModel.addRow(tbData);
                usersCount++;
            }

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No Data Found!",
                    "warning",
                    JOptionPane.WARNING_MESSAGE
            );
        }

        userCountLabel.setText(String.valueOf(usersCount) + " " + "Users");
        carsLabel.setText(String.valueOf(carsCount) + " " + "Cars Worked on");
    }

}
